#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  ln -nfs "../vendor/gocode/bin/swarm" "$shome/bin/"

  block compile service
}

bootstrap
