#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_swarm="$(swarm --version 2>&- | awk 'NR == 1 {print $3}' || true)"
  jq -n --arg swarm "$ver_swarm" '{"docker-swarm": $swarm}'
}

version "$@"
